### ISSUE TITLE
Support -tls=self-signed

### ISSUE THREAD

**Issue by joneskoo** [gokrazy/breakglass#13]
Breakglass has no option that would allow it to be used with self-signed TLS certs generated by gokr-packer -tls=self-signed. Also no -insecure flag. Since gokrazy redirects to https when TLS is in use, breakglass won't work with TLS.

I think it should trust the same certs as gokr-packer does. Probably would need to move that code under internal/ but I think this is a refactoring @stapelberg would have opinions on so probably not a good PR candidate.

**Comment by stapelberg** [comment]
Thanks for flagging this.

Moving the code from the packer into internal sounds good in general. Feel free to send a PR for it :)

**Comment by joneskoo** [comment]
I started but honestly it's a bit tricky refactor as gokr-packer uses flags and breakglass doesn't have them. Each have slightly diffferent logic how to construct URL. Also breakglass client has a Cookie jar which would maybe need to be added for the other one?

There is some parts of the logic already in internal in httpclient but it's really tighly coupled to being update not connect.

I think we quickly get to questions that are not technical as much as opinions which flags to add for breakglass and what to move.

I think breakglass should at least learn -insecure . I'm not sure if it's ideal how complex gokr-packer logic is with both URL and hostname, and the -tls flag has privatekey too which wouldn't work for breakglass. (Also it doesn't work with filenames with comma but that's not important.)

This would be nice to watch how you decide between these details if you feel like live streaming one of these days.

**Comment by stapelberg** [comment]
Did the refactoring! The -tls flag is now available in breakglass. Give it a shot and let me know if something is still not working for you.

The -gokrazy_url flag now uses the -update logic under the hood, as those two should really behave the same way.

(I’ll do some more streaming, but not quite sure when yet schedule-wise.)

**Comment by joneskoo** [comment]
Works great, now breakglass also is usable when TLS is enabled. Agree this is resolved.

A few notes:

1. I didn't test but looking at the code, I think -tls with custom certificate paths in breakglass shouldn't really need private keys at all but currently since it reuses the code from gokr-packer, it requires the private key as well. The comma delimited certificate,private-key is problematic.

2. I'm not sure if it's expected when gokrazy is set up with TLS - breakglass will work without `-tls=self-signed` (would send password over plaintext). I would have expected it to fail like I think gokr-packer does if not passing -tls but gokrazy has TLS. Passing `-tls=self-signed` requires certificate validation and works as expected. I think the root problem is that the default is insecure (no TLS) and it'd be better but backwards incompatible to always use TLS.

For breakglass I think these are acceptable caveats and sharp edges, but perhaps not broader gokrazy.

**Comment by stapelberg** [comment]
> 1. I didn't test but looking at the code, I think -tls with custom certificate paths in breakglass shouldn't really need private keys at all but currently since it reuses the code from gokr-packer, it requires the private key as well. The comma delimited certificate,private-key is problematic.

We could probably make the code ignore the private key, so that you can specify a placeholder.

> 2\. I'm not sure if it's expected when gokrazy is set up with TLS - breakglass will work without `-tls=self-signed` (would send password over plaintext)

Huh, I thought when a gokrazy instance uses TLS it does not accept any requests over plaintext anymore.

**Comment by joneskoo** [comment]
@stapelberg re: 2, True, gokrazy doesn't accept requests over plaintext. However breakglass discovers TLS and silently upgrades to TLS when -tls is not specified. So in this scenario if attacker was able to MITM and serve plain http, the credentials would be sent over plain http. A passive attacker would not be able to capture credentials as far as I can tell.

So basically this only affects breakglass with active attacker. I think gokr-packer fails if you try to update without -tls when the appliance is already using tls (need to use explicit https URL). But maybe this changed during refactor, I didn't test. I thought it was intentional to discourage from using without -tls when appliance is using tls.

**Comment by stapelberg** [comment]
Ah, you’re worried about a downgrade attack. Yeah, you currently need to use `-tls` explicitly to protect against that. We could probably write a host-specific config file on first use of `-tls` (similar to `http-port.txt`) to make the setting stick across tools.

**Comment by joneskoo** [comment]
That would be nice, and presence of keypair files would indicate same, with instruction to rm if -tls is removed intentionally.

**Comment by stapelberg** [comment]
Ah, just using the presence of keyfiles would probably be sufficient. Do you want to send a PR for that?

**Comment by joneskoo** [comment]
Not sure when I have time; life outside computers and all. If you feel like I don't mind at all if you make the change.

Otherwise I can take a look one of these days.
