### ISSUE TITLE
"sh": executable file not found in $PATH

### ISSUE THREAD

**Issue by StevenK8** [gokrazy/breakglass#4]
Hi, 

After transferring the breakglass.tar, the gokrazy output was: 
` 2019/07/24 14:35:00 breakglass.go:81: user "root" successfully authorized from remote addr 192.168.0.79:37502
  2019/07/24 14:35:00 scp.go:78: extracting "sh"
  2019/07/24 14:35:00 ssh.go:52: requests exhausted`

but when I launched a ssh session with: `ssh gokrazy@host`, gokrazy returned:
`2019/07/24 14:35:19 breakglass.go:81: user "gokrazy" successfully authorized from remote addr 192.168.0.79:37506
  2019/07/24 14:35:19 ssh.go:178: Starting cmd ["sh"]
  2019/07/24 14:35:19 ssh.go:40: request("shell"): exec: "sh": executable file not found in $PATH`
and on terminal `shell request failed on channel 0`

Do you have any idea why this happens?

Thank you

**Comment by stapelberg** [comment]
Does your tarball contain a file called `sh`? It needs to.

Can you provide the output of `tar tvf <tarball>`?

**Comment by StevenK8** [comment]
It did, but I found the problem: the busybox compiling configuration wasn't set properly. I followed these instructions and I was able to connect via ssh.


`$ Busybox Settings --> Build Options --> Build Busybox as a static binary (no shared libs)  -  Enable this option by pressing "Y"`
`$ Busybox Settings --> Build Options --> Cross compiler prefix  -  Set this option equal to "arm-linux-gnueabihf-gcc"`
`$ Busybox Settings --> Installation Options --> Don't use /usr  -  Enable this option by pressing "Y"`
`$ Linux Module Utilities --> () Default directory containing modules - Set this option to nothing`
`$ Linux Module Utilities --> () Default name of modules.dep - Set this option to nothing`
